<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<h2 class="contentTitle">请选择症状条目(至少4条)</h2>
<div class="formBar">
	<label style="float:left"><input type="checkbox" class="checkboxCtrl" group="c1" />全选</label>
	<ul>
		<li><div class="button"><div class="buttonContent"><button type="button" class="checkboxCtrl" group="c1" selectType="invert">反选</button></div></div></li>
		<li><div class="buttonActive"><div class="buttonContent"><button type="submit">提交</button></div></div></li>
	</ul>
</div>
<div class="pageContent">
	<div class="tabs" currentIndex="0" eventType="click">
		<div class="tabsHeader">
			<div class="tabsHeaderContent">
				<ul>
					<li><a href="javascript:;"><span>头面五官部</span></a></li>
					<li><a href="javascript:;"><span>胸胁腰腹部</span></a></li>
					<li><a href="javascript:;"><span>汗二阴二便</span></a></li>
					<li><a href="javascript:;"><span>手足关节部</span></a></li>
					<li><a href="javascript:;"><span>把二十一脉</span></a></li>
				</ul>
			</div>
		</div>
		<div class="tabsContent" style="height:513px;">
			<div class="pageFormContent" style="height:400px">
		<label><input type="checkbox" name="c1" value="面色白" />面色白</label>
		<label><input type="checkbox" name="c1" value="面色白带青" />面色白带青</label>
		<label><input type="checkbox" name="c1" value="面色黄色鲜" />面色黄色鲜</label>
		<label><input type="checkbox" name="c1" value="面色淡黄萎黄" />面色淡黄萎黄</label>
		<label><input type="checkbox" name="c1" value="面色红如醉" />面色红如醉</label>
		<label><input type="checkbox" name="c1" value="午后颧红" />午后颧红</label>
		<label><input type="checkbox" name="c1" value="面嫩红带白如妆" />面嫩红带白如妆</label>
		<label><input type="checkbox" name="c1" value="面色青带黑" />面色青带黑</label>
		<label><input type="checkbox" name="c1" value="面色青带红" />面色青带红</label>
		<label><input type="checkbox" name="c1" value="面青(唇、指甲青)" />面青(唇、指甲青)</label>
		<label><input type="checkbox" name="c1" value="面色黑" />面色黑</label>
		<label><input type="checkbox" name="c1" value="面色黑带淡黄" />面色黑带淡黄</label>
		<label><input type="checkbox" name="c1" value="面色黑带深黄" />面色黑带深黄</label>
		<label><input type="checkbox" name="c1" value="面色黑青暗淡" />面色黑青暗淡</label>
		<label><input type="checkbox" name="c1" value="发落枯黄干（小儿发枯黄同）" />发落枯黄干（小儿发枯黄同）</label>
		<label><input type="checkbox" name="c1" value="少年白发" />少年白发</label>
		<label><input type="checkbox" name="c1" value="发稀疏不长（小儿发迟）" />发稀疏不长（小儿发迟）</label>
		<label><input type="checkbox" name="c1" value="发细软而黄" />发细软而黄</label>
		<label><input type="checkbox" name="c1" value="突然片状脱发" />突然片状脱发</label>
		<label><input type="checkbox" name="c1" value="小儿发结如穗" />小儿发结如穗</label>
		<label><input type="checkbox" name="c1" value="囟凸（自填）" />囟凸（自填）</label>
		<label><input type="checkbox" name="c1" value="囟凹（囟陷）" />囟凹（囟陷）</label>
		<label><input type="checkbox" name="c1" value="囟门不合（解颅）" />囟门不合（解颅）</label>
		<label><input type="checkbox" name="c1" value="头摇不能自主(摇头风)" />头摇不能自主(摇头风)</label>
		<label><input type="checkbox" name="c1" value="目眦红" />目眦红</label>
		<label><input type="checkbox" name="c1" value="目睛红" />目睛红</label>
		<label><input type="checkbox" name="c1" value="目黄（白睛黄）" />目黄（白睛黄）</label>
		<label><input type="checkbox" name="c1" value="眼睑红肿" />眼睑红肿</label>
		<label><input type="checkbox" name="c1" value="下眼睑浮肿" />下眼睑浮肿</label>
		<label><input type="checkbox" name="c1" value="眼睑下垂（睑废）" />眼睑下垂（睑废）</label>
		<label><input type="checkbox" name="c1" value="天吊眼（眼球上窜）" />天吊眼（眼球上窜）</label>
		<label><input type="checkbox" name="c1" value="横目斜视" />横目斜视</label>
		<label><input type="checkbox" name="c1" value="睡露睛（睡不能闭眼）" />睡露睛（睡不能闭眼）</label>
		<label><input type="checkbox" name="c1" value="直视（睛定带眼脸不闭）" />直视（睛定带眼脸不闭）</label>
		<label><input type="checkbox" name="c1" value="羞明（畏光、闭目不开）" />羞明（畏光、闭目不开）</label>
		<label><input type="checkbox" name="c1" value="羞明红肿" />羞明红肿</label>
		<label><input type="checkbox" name="c1" value="定睛" />定睛</label>
		<label><input type="checkbox" name="c1" value="目瞑（眼睛不想睁开）" />目瞑（眼睛不想睁开）</label>
		<label><input type="checkbox" name="c1" value="目干涩" />目干涩</label>
		<label><input type="checkbox" name="c1" value="眵多稠（眼屎多稠）" />眵多稠（眼屎多稠）</label>
		<label><input type="checkbox" name="c1" value="眵多稀（眼屎多稀）" />眵多稀（眼屎多稀）</label>
		<label><input type="checkbox" name="c1" value="眼眶见黑" />眼眶见黑</label>
		<label><input type="checkbox" name="c1" value="视物昏花" />视物昏花</label>
		<label><input type="checkbox" name="c1" value="雀目（连续眨眼）" />雀目（连续眨眼）</label>
		<label><input type="checkbox" name="c1" value="目隐痛时止" />目隐痛时止</label>
		<label><input type="checkbox" name="c1" value="目胀痛无外症" />目胀痛无外症</label>
		<label><input type="checkbox" name="c1" value="目红肿痛" />目红肿痛</label>
		<label><input type="checkbox" name="c1" value="目痒" />目痒</label>
		<label><input type="checkbox" name="c1" value="眼弦赤烂" />眼弦赤烂</label>
		<label><input type="checkbox" name="c1" value="眼胞痰核" />眼胞痰核</label>
		<label><input type="checkbox" name="c1" value="斑翳初起" />斑翳初起</label>
		<label><input type="checkbox" name="c1" value="鼻头色青" />鼻头色青</label>
		<label><input type="checkbox" name="c1" value="鼻色红赤" />鼻色红赤</label>
		<label><input type="checkbox" name="c1" value="鼻头色黄" />鼻头色黄</label>
		<label><input type="checkbox" name="c1" value="鼻头色黑" />鼻头色黑</label>
		<label><input type="checkbox" name="c1" value="鼻头色白" />鼻头色白</label>
		<label><input type="checkbox" name="c1" value="鼻孔干燥" />鼻孔干燥</label>
		<label><input type="checkbox" name="c1" value="鼻流清涕" />鼻流清涕</label>
		<label><input type="checkbox" name="c1" value="鼻流浊涕（鼻渊）" />鼻流浊涕（鼻渊）</label>
		<label><input type="checkbox" name="c1" value="鼻衄（流鼻血）" />鼻衄（流鼻血）</label>
		<label><input type="checkbox" name="c1" value="鼻塞" />鼻塞</label>
		<label><input type="checkbox" name="c1" value="打喷嚏" />打喷嚏</label>
		<label><input type="checkbox" name="c1" value="耳鸣" />耳鸣</label>
		<label><input type="checkbox" name="c1" value="耳聋" />耳聋</label>
		<label><input type="checkbox" name="c1" value="上午头痛" />上午头痛</label>
		<label><input type="checkbox" name="c1" value="午后头痛" />午后头痛</label>
		<label><input type="checkbox" name="c1" value="白天头痛" />白天头痛</label>
		<label><input type="checkbox" name="c1" value="夜间头痛" />夜间头痛</label>
		<label><input type="checkbox" name="c1" value="头痛无休止（多见外感）" />头痛无休止（多见外感）</label>
		<label><input type="checkbox" name="c1" value="头时痛时止（内伤头痛）" />头时痛时止（内伤头痛）</label>
		<label><input type="checkbox" name="c1" value="头痛而沉晕" />头痛而沉晕</label>
		<label><input type="checkbox" name="c1" value="烦恼头痛加剧" />烦恼头痛加剧</label>
		<label><input type="checkbox" name="c1" value="头偏侧痛" />头偏侧痛</label>
		<label><input type="checkbox" name="c1" value="前额连眉棱骨痛" />前额连眉棱骨痛</label>
		<label><input type="checkbox" name="c1" value="后头连颈痛" />后头连颈痛</label>
		<label><input type="checkbox" name="c1" value="项强" />项强</label>
		<label><input type="checkbox" name="c1" value="头顶痛" />头顶痛</label>
		<label><input type="checkbox" name="c1" value="全头作痛" />全头作痛</label>
		<label><input type="checkbox" name="c1" value="头晕" />头晕</label>
		<label><input type="checkbox" name="c1" value="眩晕时久（目眩）" />眩晕时久（目眩）</label>
		<label><input type="checkbox" name="c1" value="妇人眩晕" />妇人眩晕</label>
		<label><input type="checkbox" name="c1" value="暴眩" />暴眩</label>
		<label><input type="checkbox" name="c1" value="脑鸣" />脑鸣</label>
		<label><input type="checkbox" name="c1" value="寒热无定时（多外感）" />寒热无定时（多外感）</label>
		<label><input type="checkbox" name="c1" value="恶寒（寒战、振寒）" />恶寒（寒战、振寒）</label>
		<label><input type="checkbox" name="c1" value="早上发热" />早上发热</label>
		<label><input type="checkbox" name="c1" value="下午发热" />下午发热</label>
		<label><input type="checkbox" name="c1" value="日晡潮热" />日晡潮热</label>
		<label><input type="checkbox" name="c1" value="夜间热重（白天低热）" />夜间热重（白天低热）</label>
		<label><input type="checkbox" name="c1" value="寒热往来" />寒热往来</label>
		<label><input type="checkbox" name="c1" value="畏热（但热不寒同）" />畏热（但热不寒同）</label>
		<label><input type="checkbox" name="c1" value="畏寒（但寒不热同）" />畏寒（但寒不热同）</label>
		<label><input type="checkbox" name="c1" value="寒热并作且有汗" />寒热并作且有汗</label>
		<label><input type="checkbox" name="c1" value="寒热并作而无汗" />寒热并作而无汗</label>
		<label><input type="checkbox" name="c1" value="烦热（心中热、五心烦热同）" />烦热（心中热、五心烦热同）</label>
		<label><input type="checkbox" name="c1" value="壮热" />壮热</label>
		<label><input type="checkbox" name="c1" value="久热不退" />久热不退</label>
		<label><input type="checkbox" name="c1" value="口咸" />口咸</label>
		<label><input type="checkbox" name="c1" value="口淡" />口淡</label>
		<label><input type="checkbox" name="c1" value="口甜" />口甜</label>
		<label><input type="checkbox" name="c1" value="口苦" />口苦</label>
		<label><input type="checkbox" name="c1" value="口酸" />口酸</label>
		<label><input type="checkbox" name="c1" value="口香（果香味）" />口香（果香味）</label>
		<label><input type="checkbox" name="c1" value="口臭" />口臭</label>
		<label><input type="checkbox" name="c1" value="口干" />口干</label>
		<label><input type="checkbox" name="c1" value="口粘" />口粘</label>
		<label><input type="checkbox" name="c1" value="口糜（口腔溃疡）" />口糜（口腔溃疡）</label>
		<label><input type="checkbox" name="c1" value="口疮（鹅口疮等）" />口疮（鹅口疮等）</label>
		<label><input type="checkbox" name="c1" value="口开齿燥" />口开齿燥</label>
		<label><input type="checkbox" name="c1" value="唇白" />唇白</label>
		<label><input type="checkbox" name="c1" value="唇黑或黯" />唇黑或黯</label>
		<label><input type="checkbox" name="c1" value="唇红" />唇红</label>
		<label><input type="checkbox" name="c1" value="唇紫红" />唇紫红</label>
		<label><input type="checkbox" name="c1" value="唇青" />唇青</label>
		<label><input type="checkbox" name="c1" value="唇肿" />唇肿</label>
		<label><input type="checkbox" name="c1" value="唇干燥" />唇干燥</label>
		<label><input type="checkbox" name="c1" value="唇蠕动（蠕动不能自主）" />唇蠕动（蠕动不能自主）</label>
		<label><input type="checkbox" name="c1" value="唇裂" />唇裂</label>
		<label><input type="checkbox" name="c1" value="唇紧（小儿不能吮乳）" />唇紧（小儿不能吮乳）</label>
		<label><input type="checkbox" name="c1" value="唇麻木" />唇麻木</label>
		<label><input type="checkbox" name="c1" value="咽痛" />咽痛</label>
		<label><input type="checkbox" name="c1" value="咽干" />咽干</label>
		<label><input type="checkbox" name="c1" value="咽喉深红（咽喉乳蛾）" />咽喉深红（咽喉乳蛾）</label>
		<label><input type="checkbox" name="c1" value="咽喉粉红色淡" />咽喉粉红色淡</label>
		<label><input type="checkbox" name="c1" value="牙龈出血" />牙龈出血</label>
		<label><input type="checkbox" name="c1" value="齿结酱瓣" />齿结酱瓣</label>
		<label><input type="checkbox" name="c1" value="牙龈缺血（萎缩）" />牙龈缺血（萎缩）</label>
		<label><input type="checkbox" name="c1" value="牙遇寒痛" />牙遇寒痛</label>
		<label><input type="checkbox" name="c1" value="牙遇热痛" />牙遇热痛</label>
		<label><input type="checkbox" name="c1" value="牙冷热皆痛(虫牙痛)" />牙冷热皆痛(虫牙痛)</label>
		<label><input type="checkbox" name="c1" value="牙齿浮摇" />牙齿浮摇</label>
		<label><input type="checkbox" name="c1" value="夜间磨牙" />夜间磨牙</label>
		<label><input type="checkbox" name="c1" value="齿燥无津" />齿燥无津</label>
		<label><input type="checkbox" name="c1" value="齿龈肿痛" />齿龈肿痛</label>
		<label><input type="checkbox" name="c1" value="牙关肿痛" />牙关肿痛</label>
		<label><input type="checkbox" name="c1" value="小儿牙齿不生" />小儿牙齿不生</label>
		<label><input type="checkbox" name="c1" value="正常人的舌象（图22）" />正常人的舌象（图22）</label>
		<label><input type="checkbox" name="c1" value="淡白苔（图3-3）" />淡白苔（图3-3）</label>
		<label><input type="checkbox" name="c1" value="白苔绛底（图63）" />白苔绛底（图63）</label>
		<label><input type="checkbox" name="c1" value="白苔舌边红" />白苔舌边红</label>
		<label><input type="checkbox" name="c1" value="苔白厚无津（图48）" />苔白厚无津（图48）</label>
		<label><input type="checkbox" name="c1" value="苔白厚有津" />苔白厚有津</label>
		<label><input type="checkbox" name="c1" value="苔白嫩滑" />苔白嫩滑</label>
		<label><input type="checkbox" name="c1" value="苔白如积粉（图3-48）" />苔白如积粉（图3-48）</label>
		<label><input type="checkbox" name="c1" value="苔薄黄（图64）" />苔薄黄（图64）</label>
		<label><input type="checkbox" name="c1" value="苔厚黄干" />苔厚黄干</label>
		<label><input type="checkbox" name="c1" value="苔黄厚滑腻（图3-4）" />苔黄厚滑腻（图3-4）</label>
		<label><input type="checkbox" name="c1" value="苔黄燥裂纹" />苔黄燥裂纹</label>
		<label><input type="checkbox" name="c1" value="灰黑苔而腻（图3-610" />灰黑苔而腻（图3-610</label>
		<label><input type="checkbox" name="c1" value="苔灰黑而干" />苔灰黑而干</label>
		<label><input type="checkbox" name="c1" value="苔黑滑润（图66）" />苔黑滑润（图66）</label>
		<label><input type="checkbox" name="c1" value="苔黑燥裂 (图51)" />苔黑燥裂 (图51)</label>
		<label><input type="checkbox" name="c1" value="苔黑滑粘腻（图66）" />苔黑滑粘腻（图66）</label>
		<label><input type="checkbox" name="c1" value="地图舌（图59）" />地图舌（图59）</label>
		<label><input type="checkbox" name="c1" value="镜面舌（图57）" />镜面舌（图57）</label>
		<label><input type="checkbox" name="c1" value="舌淡红（图27)" />舌淡红（图27)</label>
		<label><input type="checkbox" name="c1" value="舌鲜红（图29）" />舌鲜红（图29）</label>
		<label><input type="checkbox" name="c1" value="舌尖独红（图285）" />舌尖独红（图285）</label>
		<label><input type="checkbox" name="c1" value="舌红出血" />舌红出血</label>
		<label><input type="checkbox" name="c1" value="舌红中现紫" />舌红中现紫</label>
		<label><input type="checkbox" name="c1" value="舌红边有淤块" />舌红边有淤块</label>
		<label><input type="checkbox" name="c1" value="绛舌（图30）" />绛舌（图30）</label>
		<label><input type="checkbox" name="c1" value="绛舌黄白苔                      " />绛舌黄白苔                      </label>
		<label><input type="checkbox" name="c1" value="绛舌滑腻                      " />绛舌滑腻                      </label>
		<label><input type="checkbox" name="c1" value="舌绛无苔（图265）" />舌绛无苔（图265）</label>
		<label><input type="checkbox" name="c1" value="青舌（图32）" />青舌（图32）</label>
		<label><input type="checkbox" name="c1" value="紫舌嫩滑（图31）" />紫舌嫩滑（图31）</label>
		<label><input type="checkbox" name="c1" value="舌紫苔黄干（图2-20）" />舌紫苔黄干（图2-20）</label>
		<label><input type="checkbox" name="c1" value="舌淡黑而黯（图2-21）" />舌淡黑而黯（图2-21）</label>
		<label><input type="checkbox" name="c1" value="舌瘦瘪（图36）" />舌瘦瘪（图36）</label>
		<label><input type="checkbox" name="c1" value="舌肿胀 (图2-35)" />舌肿胀 (图2-35)</label>
		<label><input type="checkbox" name="c1" value="齿痕舌（胖大）（图41）" />齿痕舌（胖大）（图41）</label>
		<label><input type="checkbox" name="c1" value="舌有芒刺（图37）" />舌有芒刺（图37）</label>
		<label><input type="checkbox" name="c1" value="舌有裂纹（图40）" />舌有裂纹（图40）</label>
		<label><input type="checkbox" name="c1" value="舌强（吐字不清）" />舌强（吐字不清）</label>
		<label><input type="checkbox" name="c1" value="舌颤抖难言" />舌颤抖难言</label>
		<label><input type="checkbox" name="c1" value="舌淡嫩（图289）" />舌淡嫩（图289）</label>
		<label><input type="checkbox" name="c1" value="神情恍惚" />神情恍惚</label>
		<label><input type="checkbox" name="c1" value="沉郁（寡言、不欢)" />沉郁（寡言、不欢)</label>
		<label><input type="checkbox" name="c1" value="烦躁不宁（神乱）" />烦躁不宁（神乱）</label>
		<label><input type="checkbox" name="c1" value="疲惫（懒言同）" />疲惫（懒言同）</label>
		<label><input type="checkbox" name="c1" value="神疲（少神）" />神疲（少神）</label>
		<label><input type="checkbox" name="c1" value="昏瞀（神识不清、意识朦胧）" />昏瞀（神识不清、意识朦胧）</label>
		<label><input type="checkbox" name="c1" value="昏迷" />昏迷</label>
		<label><input type="checkbox" name="c1" value="多寐（喜眠、嗜睡）" />多寐（喜眠、嗜睡）</label>
		<label><input type="checkbox" name="c1" value="易醒" />易醒</label>
		<label><input type="checkbox" name="c1" value="失眠（少睡、不得卧、不寐）" />失眠（少睡、不得卧、不寐）</label>
		<label><input type="checkbox" name="c1" value="嗜卧欲寐" />嗜卧欲寐</label>
		<label><input type="checkbox" name="c1" value="老年神疲" />老年神疲</label>
		<label><input type="checkbox" name="c1" value="多梦" />多梦</label>
		<label><input type="checkbox" name="c1" value="不能平卧" />不能平卧</label>
		<label><input type="checkbox" name="c1" value="健忘（善忘、多忘）" />健忘（善忘、多忘）</label>
		<label><input type="checkbox" name="c1" value="叹息（闷闷不乐、抑郁不舒、情志不遂）" />叹息（闷闷不乐、抑郁不舒、情志不遂）</label>
		<label><input type="checkbox" name="c1" value="易怒（急躁） " />易怒（急躁） </label>
		<label><input type="checkbox" name="c1" value="语蹇（中风）" />语蹇（中风）</label>
		<label><input type="checkbox" name="c1" value="自语" />自语</label>
		<label><input type="checkbox" name="c1" value="胡言狂语" />胡言狂语</label>
		<label><input type="checkbox" name="c1" value="口眼㖞斜（眼睑不能闭合）" />口眼㖞斜（眼睑不能闭合）</label>
		<label><input type="checkbox" name="c1" value="头面重大（大头瘟毒）" />头面重大（大头瘟毒）</label>
		<label><input type="checkbox" name="c1" value="浮肿（面浮、睑肿）" />浮肿（面浮、睑肿）</label>
		<label><input type="checkbox" name="c1" value="声高重浊" />声高重浊</label>
		<label><input type="checkbox" name="c1" value="声低轻清" />声低轻清</label>
		<label><input type="checkbox" name="c1" value="谵语（声粗、语无伦次）" />谵语（声粗、语无伦次）</label>
		<label><input type="checkbox" name="c1" value="郑声（短细作语）" />郑声（短细作语）</label>
		<label><input type="checkbox" name="c1" value="失音（暴暗属实）" />失音（暴暗属实）</label>
		<label><input type="checkbox" name="c1" value="嘶哑（久暗属虚）" />嘶哑（久暗属虚）</label>
		<label><input type="checkbox" name="c1" value="喘促（咳甚则喘同）" />喘促（咳甚则喘同）</label>
		<label><input type="checkbox" name="c1" value="哮（痰鸣同）" />哮（痰鸣同）</label>
		<label><input type="checkbox" name="c1" value="上气急（呼多吸少）" />上气急（呼多吸少）</label>
		<label><input type="checkbox" name="c1" value="短气（呼吸不续）" />短气（呼吸不续）</label>
		<label><input type="checkbox" name="c1" value="少气（不能多言）" />少气（不能多言）</label>
		<label><input type="checkbox" name="c1" value="打呵欠" />打呵欠</label>
		<label><input type="checkbox" name="c1" value="气粗" />气粗</label>
		<label><input type="checkbox" name="c1" value="鼻煽（气急）" />鼻煽（气急）</label>
		<label><input type="checkbox" name="c1" value="干咳（痰极少难咯出）" />干咳（痰极少难咯出）</label>
		<label><input type="checkbox" name="c1" value="咳声重浊" />咳声重浊</label>
		<label><input type="checkbox" name="c1" value="咳声无力" />咳声无力</label>
		<label><input type="checkbox" name="c1" value="夜咳较重" />夜咳较重</label>
		<label><input type="checkbox" name="c1" value="咳则尿出" />咳则尿出</label>
		<label><input type="checkbox" name="c1" value="咳则汗出" />咳则汗出</label>
		<label><input type="checkbox" name="c1" value="咳引腰痛" />咳引腰痛</label>
		<label><input type="checkbox" name="c1" value="痰嗽（痰涎多）" />痰嗽（痰涎多）</label>
		<label><input type="checkbox" name="c1" value="痰稠粘黄" />痰稠粘黄</label>
		<label><input type="checkbox" name="c1" value="痰清白" />痰清白</label>
		<label><input type="checkbox" name="c1" value="痰带血" />痰带血</label>
		<label><input type="checkbox" name="c1" value="痰挟脓（肺痈）" />痰挟脓（肺痈）</label>
		<label><input type="checkbox" name="c1" value="呕吐与恶心" />呕吐与恶心</label>
		<label><input type="checkbox" name="c1" value="呃逆" />呃逆</label>
		<label><input type="checkbox" name="c1" value="呃声快" />呃声快</label>
		<label><input type="checkbox" name="c1" value="呃声慢" />呃声慢</label>
		<label><input type="checkbox" name="c1" value="嗳气" />嗳气</label>
			</div>
			<div class="pageFormContent" style="height:400px">
		<label><input type="checkbox" name="c1" value="胁痛胁胀" />胁痛胁胀</label>
		<label><input type="checkbox" name="c1" value="心前区绞痛" />心前区绞痛</label>
		<label><input type="checkbox" name="c1" value="胸胁牵引痛（放射到右肩）" />胸胁牵引痛（放射到右肩）</label>
		<label><input type="checkbox" name="c1" value="胸胁胀满闷" />胸胁胀满闷</label>
		<label><input type="checkbox" name="c1" value="胸胁窒闷（气闷）" />胸胁窒闷（气闷）</label>
		<label><input type="checkbox" name="c1" value="心跳过速" />心跳过速</label>
		<label><input type="checkbox" name="c1" value="心慌（心悸）" />心慌（心悸）</label>
		<label><input type="checkbox" name="c1" value="自觉闷乱不宁（心中懊侬）" />自觉闷乱不宁（心中懊侬）</label>
		<label><input type="checkbox" name="c1" value="胸闷" />胸闷</label>
		<label><input type="checkbox" name="c1" value="胸痞" />胸痞</label>
		<label><input type="checkbox" name="c1" value="心胸发热" />心胸发热</label>
		<label><input type="checkbox" name="c1" value="乳痈（胀痛）" />乳痈（胀痛）</label>
		<label><input type="checkbox" name="c1" value="乳岩（坚硬推不移）" />乳岩（坚硬推不移）</label>
		<label><input type="checkbox" name="c1" value="乳癖（硬不坚推可移）" />乳癖（硬不坚推可移）</label>
		<label><input type="checkbox" name="c1" value="乳头出血（乳衄）" />乳头出血（乳衄）</label>
		<label><input type="checkbox" name="c1" value="乳汁自流" />乳汁自流</label>
		<label><input type="checkbox" name="c1" value="不思饮（少饮喜热饮）" />不思饮（少饮喜热饮）</label>
		<label><input type="checkbox" name="c1" value="口渴不欲饮" />口渴不欲饮</label>
		<label><input type="checkbox" name="c1" value="口渴思饮" />口渴思饮</label>
		<label><input type="checkbox" name="c1" value="不思食（纳呆）" />不思食（纳呆）</label>
		<label><input type="checkbox" name="c1" value="饥而不欲食" />饥而不欲食</label>
		<label><input type="checkbox" name="c1" value="多食易饥" />多食易饥</label>
		<label><input type="checkbox" name="c1" value="食入闷胀" />食入闷胀</label>
		<label><input type="checkbox" name="c1" value="不食亦胀" />不食亦胀</label>
		<label><input type="checkbox" name="c1" value="胃痞满胀痛" />胃痞满胀痛</label>
		<label><input type="checkbox" name="c1" value="胃脘刺胀痛（夜重）" />胃脘刺胀痛（夜重）</label>
		<label><input type="checkbox" name="c1" value="胃脘灼痛" />胃脘灼痛</label>
		<label><input type="checkbox" name="c1" value="嘈杂" />嘈杂</label>
		<label><input type="checkbox" name="c1" value="腹鸣无痛" />腹鸣无痛</label>
		<label><input type="checkbox" name="c1" value="腹水肿" />腹水肿</label>
		<label><input type="checkbox" name="c1" value="腹水胀" />腹水胀</label>
		<label><input type="checkbox" name="c1" value="腹胀满" />腹胀满</label>
		<label><input type="checkbox" name="c1" value="矢气（放屁多）" />矢气（放屁多）</label>
		<label><input type="checkbox" name="c1" value="腹有痞块" />腹有痞块</label>
		<label><input type="checkbox" name="c1" value="腹反跳痛（内痈）" />腹反跳痛（内痈）</label>
		<label><input type="checkbox" name="c1" value="腹隐痛" />腹隐痛</label>
		<label><input type="checkbox" name="c1" value="少腹痛（疝气）" />少腹痛（疝气）</label>
		<label><input type="checkbox" name="c1" value="妇女痛经" />妇女痛经</label>
		<label><input type="checkbox" name="c1" value="小腹痛" />小腹痛</label>
		<label><input type="checkbox" name="c1" value="小腹二侧痛" />小腹二侧痛</label>
		<label><input type="checkbox" name="c1" value="绕脐痛" />绕脐痛</label>
		<label><input type="checkbox" name="c1" value="里急后重（痢疾脱肛）" />里急后重（痢疾脱肛）</label>
		<label><input type="checkbox" name="c1" value="肠鸣腹痛（每鸣必痛）" />肠鸣腹痛（每鸣必痛）</label>
		<label><input type="checkbox" name="c1" value="腰发沉痛" />腰发沉痛</label>
		<label><input type="checkbox" name="c1" value="腰酸软痛" />腰酸软痛</label>
		<label><input type="checkbox" name="c1" value="运动则痛减" />运动则痛减</label>
		<label><input type="checkbox" name="c1" value="下肢运动则痛" />下肢运动则痛</label>
		<label><input type="checkbox" name="c1" value="全身疼痛" />全身疼痛</label>
		<label><input type="checkbox" name="c1" value="身痛（有寒热）" />身痛（有寒热）</label>
		<label><input type="checkbox" name="c1" value="产后身痛" />产后身痛</label>
		<label><input type="checkbox" name="c1" value="身热而痛" />身热而痛</label>
		<label><input type="checkbox" name="c1" value="身体沉痛（酸困）" />身体沉痛（酸困）</label>
		<label><input type="checkbox" name="c1" value="身体倦怠" />身体倦怠</label>
		<label><input type="checkbox" name="c1" value="清瘦（精神尚可）" />清瘦（精神尚可）</label>
		<label><input type="checkbox" name="c1" value="瘦弱（精神不足）" />瘦弱（精神不足）</label>
		<label><input type="checkbox" name="c1" value="振颤" />振颤</label>
		<label><input type="checkbox" name="c1" value="枯涩（肌肉无弹性）" />枯涩（肌肉无弹性）</label>
		<label><input type="checkbox" name="c1" value="肥胖" />肥胖</label>
		<label><input type="checkbox" name="c1" value="角弓反张" />角弓反张</label>
		<label><input type="checkbox" name="c1" value="肌肤甲错（内生痈脓）" />肌肤甲错（内生痈脓）</label>
		<label><input type="checkbox" name="c1" value="偏枯（半身不遂）" />偏枯（半身不遂）</label>
		<label><input type="checkbox" name="c1" value="胸胁刺痛（胸痛、心前区隐痛）" />胸胁刺痛（胸痛、心前区隐痛）</label>
	</div>
	<div class="pageFormContent" style="height:400px">
		<label><input type="checkbox" name="c1" value="醒时出汗（自汗）" />醒时出汗（自汗）</label>
		<label><input type="checkbox" name="c1" value="睡时出汗（盗汗）" />睡时出汗（盗汗）</label>
		<label><input type="checkbox" name="c1" value="微汗" />微汗</label>
		<label><input type="checkbox" name="c1" value="大汗（大汗不止）" />大汗（大汗不止）</label>
		<label><input type="checkbox" name="c1" value="粘手汗（汗出如油）" />粘手汗（汗出如油）</label>
		<label><input type="checkbox" name="c1" value="黄汗" />黄汗</label>
		<label><input type="checkbox" name="c1" value="动则汗出" />动则汗出</label>
		<label><input type="checkbox" name="c1" value="尿少而肿（小便闭）" />尿少而肿（小便闭）</label>
		<label><input type="checkbox" name="c1" value="尿量多（消渴病）" />尿量多（消渴病）</label>
		<label><input type="checkbox" name="c1" value="夜尿多" />夜尿多</label>
		<label><input type="checkbox" name="c1" value="尿频（次数多）不痛" />尿频（次数多）不痛</label>
		<label><input type="checkbox" name="c1" value="尿次多（量少且痛）" />尿次多（量少且痛）</label>
		<label><input type="checkbox" name="c1" value="尿崩（排尿时控制不住）" />尿崩（排尿时控制不住）</label>
		<label><input type="checkbox" name="c1" value="小便带血" />小便带血</label>
		<label><input type="checkbox" name="c1" value="小便臊味" />小便臊味</label>
		<label><input type="checkbox" name="c1" value="小便混浊" />小便混浊</label>
		<label><input type="checkbox" name="c1" value="小便赤涩痛（淋证）" />小便赤涩痛（淋证）</label>
		<label><input type="checkbox" name="c1" value="小便失禁" />小便失禁</label>
		<label><input type="checkbox" name="c1" value="大便难出（无力出便）" />大便难出（无力出便）</label>
		<label><input type="checkbox" name="c1" value="便秘（便干同）" />便秘（便干同）</label>
		<label><input type="checkbox" name="c1" value="便泄（腹痛即泻）" />便泄（腹痛即泻）</label>
		<label><input type="checkbox" name="c1" value="便溏" />便溏</label>
		<label><input type="checkbox" name="c1" value="便溏而不爽" />便溏而不爽</label>
		<label><input type="checkbox" name="c1" value="大便稀" />大便稀</label>
		<label><input type="checkbox" name="c1" value="水样便（水泄）" />水样便（水泄）</label>
		<label><input type="checkbox" name="c1" value="大便带血（血便）" />大便带血（血便）</label>
		<label><input type="checkbox" name="c1" value="大便带脓（脓便）" />大便带脓（脓便）</label>
		<label><input type="checkbox" name="c1" value="完谷不化" />完谷不化</label>
		<label><input type="checkbox" name="c1" value="大便酸臭" />大便酸臭</label>
		<label><input type="checkbox" name="c1" value="大便腥臭" />大便腥臭</label>
		<label><input type="checkbox" name="c1" value="大便恶臭" />大便恶臭</label>
		<label><input type="checkbox" name="c1" value="吐泻不止" />吐泻不止</label>
		<label><input type="checkbox" name="c1" value="只泻不吐" />只泻不吐</label>
		<label><input type="checkbox" name="c1" value="阴痒" />阴痒</label>
		<label><input type="checkbox" name="c1" value="前阴抽痛" />前阴抽痛</label>
		<label><input type="checkbox" name="c1" value="阳痿" />阳痿</label>
		<label><input type="checkbox" name="c1" value="早泄" />早泄</label>
		<label><input type="checkbox" name="c1" value="遗精（梦遗）" />遗精（梦遗）</label>
		<label><input type="checkbox" name="c1" value="滑精（白日精自流）" />滑精（白日精自流）</label>
		<label><input type="checkbox" name="c1" value="脱肛" />脱肛</label>
		<label><input type="checkbox" name="c1" value="肛裂" />肛裂</label>
		<label><input type="checkbox" name="c1" value="肛痒" />肛痒</label>
		<label><input type="checkbox" name="c1" value="月经提前" />月经提前</label>
		<label><input type="checkbox" name="c1" value="月经推后" />月经推后</label>
		<label><input type="checkbox" name="c1" value="月经前后无定期（痛经）" />月经前后无定期（痛经）</label>
		<label><input type="checkbox" name="c1" value="月经过多（血崩同）" />月经过多（血崩同）</label>
		<label><input type="checkbox" name="c1" value="月经涩少" />月经涩少</label>
		<label><input type="checkbox" name="c1" value="月经结块" />月经结块</label>
		<label><input type="checkbox" name="c1" value="经色鲜红" />经色鲜红</label>
		<label><input type="checkbox" name="c1" value="月经色淡" />月经色淡</label>
		<label><input type="checkbox" name="c1" value="经前腹痛（痛经）" />经前腹痛（痛经）</label>
		<label><input type="checkbox" name="c1" value="经后腹痛（痛经）" />经后腹痛（痛经）</label>
		<label><input type="checkbox" name="c1" value="经色紫暗" />经色紫暗</label>
		<label><input type="checkbox" name="c1" value="闭经" />闭经</label>
		<label><input type="checkbox" name="c1" value="白带" />白带</label>
		<label><input type="checkbox" name="c1" value="黄带" />黄带</label>
		<label><input type="checkbox" name="c1" value="赤白带" />赤白带</label>
		<label><input type="checkbox" name="c1" value="带下腥臭" />带下腥臭</label>
		<label><input type="checkbox" name="c1" value="带下稠臭" />带下稠臭</label>
		<label><input type="checkbox" name="c1" value="五色带下" />五色带下</label>
		<label><input type="checkbox" name="c1" value="性欲减退" />性欲减退</label>
		<label><input type="checkbox" name="c1" value="性欲亢奋" />性欲亢奋</label>
	</div>
			<div class="pageFormContent" style="height:400px">
		<label><input type="checkbox" name="c1" value="急惊风（手足抽搐、痉病）" />急惊风（手足抽搐、痉病）</label>
		<label><input type="checkbox" name="c1" value="小儿慢惊风" />小儿慢惊风</label>
		<label><input type="checkbox" name="c1" value="足未痿不能行（痿病）" />足未痿不能行（痿病）</label>
		<label><input type="checkbox" name="c1" value="肉已痿不能行（痿病）" />肉已痿不能行（痿病）</label>
		<label><input type="checkbox" name="c1" value="手足拘急（鸡爪风）" />手足拘急（鸡爪风）</label>
		<label><input type="checkbox" name="c1" value="屈而不伸" />屈而不伸</label>
		<label><input type="checkbox" name="c1" value="伸而不屈（四肢僵直）" />伸而不屈（四肢僵直）</label>
		<label><input type="checkbox" name="c1" value="手足颤抖" />手足颤抖</label>
		<label><input type="checkbox" name="c1" value="站坐不稳" />站坐不稳</label>
		<label><input type="checkbox" name="c1" value="手握" />手握</label>
		<label><input type="checkbox" name="c1" value="四肢枯槁" />四肢枯槁</label>
		<label><input type="checkbox" name="c1" value="下肢水肿" />下肢水肿</label>
		<label><input type="checkbox" name="c1" value="四肢抽痛（挛急同）" />四肢抽痛（挛急同）</label>
		<label><input type="checkbox" name="c1" value="筋骨痛" />筋骨痛</label>
		<label><input type="checkbox" name="c1" value="肢体麻木" />肢体麻木</label>
		<label><input type="checkbox" name="c1" value="四肢冷" />四肢冷</label>
		<label><input type="checkbox" name="c1" value="下肢冷" />下肢冷</label>
		<label><input type="checkbox" name="c1" value="四肢刺痛" />四肢刺痛</label>
		<label><input type="checkbox" name="c1" value="手足心热" />手足心热</label>
		<label><input type="checkbox" name="c1" value="关节红肿痛" />关节红肿痛</label>
		<label><input type="checkbox" name="c1" value="关节冷痛" />关节冷痛</label>
		<label><input type="checkbox" name="c1" value="关节肿痛不红" />关节肿痛不红</label>
	</div>
			<div class="pageFormContent" style="height:400px">
			<label><input type="checkbox" name="c1" value="浮脉" />浮脉</label>
			<label><input type="checkbox" name="c1" value="洪脉" />洪脉</label>
			<label><input type="checkbox" name="c1" value="濡脉" />濡脉</label>
			<label><input type="checkbox" name="c1" value="芤脉" />芤脉</label>
			<label><input type="checkbox" name="c1" value="沉脉" />沉脉</label>
			<label><input type="checkbox" name="c1" value="弱脉" />弱脉</label>
			<label><input type="checkbox" name="c1" value="迟脉" />迟脉</label>
			<label><input type="checkbox" name="c1" value="涩脉" />涩脉</label>
			<label><input type="checkbox" name="c1" value="结脉" />结脉</label>
			<label><input type="checkbox" name="c1" value="数脉" />数脉</label>
			<label><input type="checkbox" name="c1" value="促脉" />促脉</label>
			<label><input type="checkbox" name="c1" value="虚脉" />虚脉</label>
			<label><input type="checkbox" name="c1" value="细脉" />细脉</label>
			<label><input type="checkbox" name="c1" value="微脉" />微脉</label>
			<label><input type="checkbox" name="c1" value="代脉" />代脉</label>
			<label><input type="checkbox" name="c1" value="实脉" />实脉</label>
			<label><input type="checkbox" name="c1" value="滑脉" />滑脉</label>
			<label><input type="checkbox" name="c1" value="弦脉" />弦脉</label>
			<label><input type="checkbox" name="c1" value="紧脉" />紧脉</label>
			<label><input type="checkbox" name="c1" value="长脉" />长脉</label>
			<label><input type="checkbox" name="c1" value="大脉" />大脉</label>
		</div>
		</div>
	</div>
</div>